accelerator: gpu
batch_size: 32
data_augmentation: True
datamodule: celeba
devices: 1
lr: 1e-3
max_epochs: 15
model: resnet
momentum: 0.9
optimizer: sgd
refresh_rate: 2600
resnet_pretrained: True
resnet_version: 50
weight_decay: 1e-4
