accelerator: gpu
batch_size: 256
check_val_every_n_epoch: 10
ckpt_every_n_epoch: 10
cnn_initial_width: 16
cnn_num_layers: 3
datamodule: cifar10
devices: 1
lr: 0.05
max_epochs: 30
mlp_hidden_dim: 128
mlp_num_layers: 2
model: resnet
resnet_small_input: True
resnet_version: 18
weight_decay: 0
