accelerator: gpu
batch_size: 256
check_val_every_n_epoch: 10
ckpt_every_n_epoch: 10
datamodule: cifar10
devices: 1
dropout_prob: 0.5
lr: 0.1
lr_drop: 0.1
lr_steps: [20, 40]
max_epochs: 50
model: resnet
resnet_small_input: True
