batch_size: 256
data_dir: data
dropout_probability: 0.5
gpus: 1
lr: 0.02
lr_drop: 0.1
lr_steps: [30, 40, 45]
max_epochs: 50
momentum: 0.9
optimizer: sgd
refresh_rate: 18
resnet_version: 50
resume_training: False
resume_weights: False
train_fc_only: False
val_split: 0.2
weights: ""
weight_decay: 1e-4
workers: 4
