arch: mlp
batch_size: 256
classes: 10
data_dir: data
dataset: mnist
dropout_prob: 0
gpus: 1
lr: 0.05
lr_drop: 0.1
lr_steps: []
max_epochs: 1000
mlp_activation: relu
mlp_bias: True
mlp_hidden_dim: 512
mlp_input_dim: 784
mlp_num_layers: 2
momentum: 0.9
optimizer: sgd
out_dir: out
refresh_rate: 1
resnet_pretrained: True
resnet_version: 18
resume_training: False
resume_weights: False
train_fc_only: False
weights: ""
weight_decay: 0
workers: 4
