arch: resnet
batch_size: 256
classes: 10
data_dir: data
dataset: mnist
dropout_prob: 0.5
gpus: 1
lr: 0.02
lr_drop: 0.1
lr_steps: []
max_epochs: 20
mlp_activation: relu
mlp_hidden_dim: 256
mlp_input_dim: 784
mlp_num_layers: 3
momentum: 0.9
optimizer: sgd
out_dir: out
refresh_rate: 50
resnet_pretrained: True
resnet_version: 50
resume_training: False
resume_weights: False
train_fc_only: False
weights: ""
weight_decay: 1e-4
workers: 4
