accelerator: gpu
arch: cnn
batch_size: 256
bias: True
classes: 10
cnn_initial_width: 32
cnn_input_dim: 3
cnn_kernel_size: 3
cnn_num_layers: 4
cnn_padding: 1
data_augmentation: True
data_dir: data
dataset: cifar10
dropout_prob: 0
gpus: 1
lr: 1e-3
lr_drop: 0.1
lr_steps: []
max_epochs: 1000
mlp_activation: relu
mlp_hidden_dim: 256
mlp_input_dim: 3072
mlp_num_layers: 3
momentum: 0.9
nin_input_dim: 3
nin_num_layers: 2
nin_padding: 1
nin_width: 192
optimizer: adamw
out_dir: out
refresh_rate: 50
resnet_pretrained: True
resnet_version: 50
resume_training: False
resume_weights: False
train_fc_only: False
val_split: 0
weights: ""
weight_decay: 1e-4
workers: 4
