accelerator: gpu
batch_size: 256
bias: False
cnn_batchnorm: True
cnn_initial_width: 32
cnn_kernel_size: 3
cnn_num_layers: 5
cnn_padding: 1
data_augmentation: False
data_dir: data
dataset: binary_mnist
devices: 1
dropout_prob: 0
input_channels: 1
label_noise: 0
loss: mse
lr: 0.05
lr_drop: 0.1
lr_steps: []
max_epochs: 1000
model: cnn
mlp_activation: relu
mlp_hidden_dim: 256
mlp_input_dim: 784
mlp_num_layers: 2
momentum: 0.9
nin_input_dim: 3
nin_num_layers: 2
nin_padding: 1
nin_width: 192
num_workers: 4
optimizer: sgd
out_dir: out
refresh_rate: 50
resnet_pretrained: True
resnet_version: 50
resume_training: False
resume_weights: False
seed: 42
train_fc_only: False
val_split: 0
weights: ""
weight_decay: 0
