accelerator: gpu
batch_size: 32
data_augmentation: True
datamodule: waterbirds
devices: 1
lr: 1e-3
max_epochs: 100
model: resnet
momentum: 0.9
num_workers: 4
optimizer: sgd
refresh_rate: 150
resnet_pretrained: True
resnet_version: 50
weight_decay: 1e-4
