accelerator: gpu
batch_size: 32
cnn_batchnorm: True
cnn_initial_width: 32
cnn_kernel_size: 3
cnn_num_layers: 5
cnn_padding: 0
data_augmentation: True
datamodule: waterbirds
devices: 1
lr: 1e-5
max_epochs: 50
model: resnet
refresh_rate: 50
resnet_pretrained: True
resnet_version: 152
