accelerator: gpu
batch_size: 32
data_augmentation: True
datamodule: waterbirds
devices: 1
lr: 1e-3
max_epochs: 50
model: resnet
momentum: 0.9
optimizer: sgd
refresh_rate: 50
resnet_pretrained: True
resnet_version: 50
